# Generated by Django 5.1.4 on 2024-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('published_year', models.IntegerField()),
                ('availability_status', models.IntegerField(default=1)),
            ],
        ),
    ]
